services:
  web-api-app:
    image: web-api
    build: 
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "5687:5687"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - .:/src

  web-client-app:
    image: react-client
    build: 
      context: ./react-client-app
    ports:
      - "5272:5272"
    volumes:
      - ./react-client-app:/app
      - /app/node_modules